version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"            # Location of your requirements.txt file
    schedule:
      interval: "daily"       # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 5
    # Optional: ignore certain dependencies or versions
    # ignore:
    #   - dependency-name: "django"
    #     versions:
    #       - "2.x.x"
